CREATE TABLE customer (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  cpf VARCHAR(20) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  income DECIMAL(15,2) NOT NULL,
  zip_code VARCHAR(20) NOT NULL,
  street VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE credit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  credit_code UUID NOT NULL UNIQUE,
  credit_value DECIMAL(15,2) NOT NULL,
  day_first_installment DATE NOT NULL,
  number_of_installments INT NOT NULL,
  status VARCHAR(32),
  customer_id BIGINT,
  CONSTRAINT fk_credit_customer FOREIGN KEY (customer_id) REFERENCES customer(id)
);
CREATE INDEX idx_credit_customer_id ON credit(customer_id);